# This workflow generates the Windows installer (MSI)
# It must be executed manually
name: Build the MSI Package

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies on Windows
      - name: Install dependencies on Windows
        id: install-deps
        run: |
          choco install cmake -y
          choco install wixtoolset -y
          $choco_log = choco install wxwidgets -y --log-file 'choco.log'
          # Find the line in the log file that contains the deployment path
          $wxPathLine = Get-Content 'choco.log' | Where-Object { $_ -match "Deployed to" }
          # Extract the path by removing the prefix and single quotes
          $wxPath = $wxPathLine -replace ".*Deployed to '", "" -replace "'.*"
          Write-Host "The wxWidgets package was deployed to: $wxPath"
          # Set WXWIN environment variable for subsequent steps
          echo "WXWIN=$wxPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          # Add WiX to PATH for this step and subsequent steps
          $wixPath = (Get-ChildItem "C:\Program Files (x86)\WiX Toolset v*" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          echo "$wixPath\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Debug wxWidgets directory
        run: |
          Get-ChildItem -Path "$env:WXWIN" -Recurse
          # To see library files
          Get-ChildItem -Path "$env:WXWIN/lib/vc_lib"

      # Configure CMake
      - name: Configure CMake
        run: |
          Write-Host "The value of WXWIN is: $env:WXWIN"
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 `
            -DwxWidgets_USE_LIBS="core;base;html"
        working-directory: ${{ github.workspace }}

      # Generate the MSI package
      - name: Generate the MSI package
        run: |
          # Set WIXTARGETS environment variable for MSBuild
          $wixPath = (Get-ChildItem "C:\Program Files (x86)\WiX Toolset v*" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          echo "WIXTARGETS=$wixPath\Wix.targets" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          msbuild agrilla.wixproj /p:Configuration=Release
        working-directory: ${{ github.workspace }}

      # Upload MSI artifact
      - name: Upload MSI package
        uses: actions/upload-artifact@v4
        with:
          name: agrilla-msi-installer
          path: bin/Release/agrilla.msi

