# This workflow generates the Windows installer (MSI)
# It must be executed manually
name: Build the MSI Package

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies on Windows
        run: |
          choco install cmake -y
          cmake --version
          choco install wixtoolset -y
          $wixPath = (Get-ChildItem "C:\Program Files (x86)\WiX Toolset v*" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          echo "$wixPath\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install wxwidgets -y
          $wxwin = (Get-ChildItem "C:\Program Files\wxWidgets*" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          echo "WXWIN=$wxwin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
        working-directory: ${{ github.workspace }}

      - name: Build CMake project
        run: cmake --build . --config Release
        working-directory: ${{ github.workspace }}/build

      - name: Generate the MSI package
        run: |
          $wixPath = (Get-ChildItem "C:\Program Files (x86)\WiX Toolset v*" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          echo "WIXTARGETS=$wixPath\Wix.targets" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          msbuild agrilla.wixproj /p:Configuration=Release

      - name: Upload MSI package
        uses: actions/upload-artifact@v4
        with:
          name: agrilla-msi-installer
          path: bin/Release/agrilla.msi

